# Generated by Django 4.2.6 on 2024-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctioncategory_bids_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imageUrl',
            field=models.TextField(default='empty'),
        ),
    ]
